### PR TITLE
Fixed and enforced linting

### PR DESCRIPTION
**Pull request by HariAmoor-professional**
Enforces linting and fixes style problems

### CODE REVIEW

**Comment by anton-k** [comment]
Please don't use formolou, it makes code harder to read. 

I'm against deleting the alignment spaces. Especially in type declarations.
And formolou gives no choice on this topic.  I've looked up high quality code GHC, base, text
and they all use alignment with spaces which formolou destroys.

**Comment by hariamoor-mlabs** [comment]
@samuelWilliams99 Can I close this?

**Comment by samuelWilliams99** [comment]
Can we find a formatter that does enforce the style you want here then? I really don't like not having a formatter at all, everyone makes mistakes, and without a formatter, those get merged.
Like the inline case statement we refactored in this PR, I don't want to keep something like that in any repo, its meaning was somewhat ambiguous to a scanning eye.

**Comment by AriFordsham** [comment]
Would this help? https://github.com/fourmolu/fourmolu/pull/94

**Comment by AriFordsham** [comment]
Superseded by #62

**Pull request closed without merging**
