### PR TITLE
Las/ghc9

### PR DESCRIPTION
**Pull request by L-as**

### CODE REVIEW

**Comment by L-as** [comment]
,format
,lint
in shell

**Comment by anton-k** [comment]
Please return back git-hub actions they including gh-pages, they are responsible for docs building

**Comment by anton-k** [comment]
Don't use formatter, it makes code ugly.

Or I can agree with that if it will not eliminate spaces inside type definitions if there is options to turn it off.
Spaces in type definitions make types look much better to read.

**Comment by L-as** [comment]
What docs? Should be built through Hydra. There should be a formatter IMO, but you can check fourmolu options or see if there's a better one.

**Comment by anton-k** [comment]
I publish docs online with github pages:

https://mlabs-haskell.github.io/plutus-simple-model/
It's cool feature that github provides. They are auto-updated on every push to master

**Comment by L-as** [comment]
@anton-k What program do you use to build it?

**Comment by anton-k** [comment]
mdbook

**Pull request closed without merging**
