### PR TITLE
add `nix run .#docs`

### PR DESCRIPTION
**Pull request by Geometer1729**
Currently using https://github.com/mlabs-haskell/mlabs-tooling.nix/pull/25 after that's merge this can point to master.

### CODE REVIEW

**Comment by AriFordsham** [comment]
Must this be enabled per-project? Can it not be included by default from tooling?

**Comment by Geometer1729** [comment]
> Must this be enabled per-project? Can it not be included by default from tooling?

That's probably possible. I couldn't figure it out :man_shrugging:

**Comment by AriFordsham** [comment]
Can you try and chase it up?

**Comment by Geometer1729** [comment]
> Can you try and chase it up?

I have it another go and got it working fairly painlessly :) guess I'll put this back in draft mode and have it use that branch.
https://github.com/mlabs-haskell/mlabs-tooling.nix/pull/31

**Comment by Geometer1729** [comment]
This PR is now just a format change to `flake.nix` (one of the lines was over 80) and an `flake.lock `update, but it works!

**Pull request merged**
