### PR TITLE
Update dependencies and clean-up Nix a tiny bit

### PR DESCRIPTION
**Pull request by L-as**

### CODE REVIEW

**Comment by anton-k** [comment]
Is the latest plutus always compatible with latest cardano-ledger?

**Comment by L-as** [comment]
Nope. I just found out that cardano-ledger uses the release branch. I think we might have to switch Plutarch to it too.

**Comment by L-as** [comment]
This also needs some extra constraints and `allow-newer` for minor things.

**Comment by anton-k** [comment]
So maybe it's better then to mention release branch for plutus in the flakes insstead of ommiting all commit hashes?

**Comment by L-as** [comment]
This is also related to https://github.com/Plutonomicon/plutarch-plutus/issues/525

**Comment by anton-k** [comment]
I'm happy to merge it if plutus dep will somehow depend on what cardano-ledger expects.
Is it possible to achieve with `follows` or pining it to specific branch?

**Comment by L-as** [comment]
We need to fix cardano-ledger first unfortunately.

**Comment by L-as** [comment]
#52

**Pull request closed without merging**
